# Generated by Django 3.0.7 on 2020-06-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsApp', '0003_schedules_scheduleslotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingsApp.Days')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingsApp.Schedules')),
            ],
        ),
    ]
